const countries = [
  { value: 'Finland' },
  { value: 'Ireland' },
  { value: 'Norway' },
  { value: 'France' },
  { value: 'Netherlands' },
  { value: 'Japan' },
  { value: 'Sweden' },
  { value: 'Canada' },
  { value: 'United Kingdom' },
  { value: 'Portugal' },
  { value: 'Switzerland' },
  { value: 'Austria' },
  { value: 'United States' },
  { value: 'Denmark' },
  { value: 'New Zealand' },
  { value: 'Czech Republic' },
  { value: 'Belgium' },
  { value: 'Costa Rica' },
  { value: 'Germany' },
  { value: 'Spain' },
  { value: 'Poland' },
  { value: 'Australia' },
  { value: 'Israel' },
  { value: 'Chile' },
  { value: 'China' },
  { value: 'Italy' },
  { value: 'Singapore' },
  { value: 'Bulgaria' },
  { value: 'Qatar' },
  { value: 'Greece' },
  { value: 'Kazakhstan' },
  { value: 'Uruguay' },
  { value: 'Hungary' },
  { value: 'Oman' },
  { value: 'Slovakia' },
  { value: 'Peru' },
  { value: 'Bahrain' },
  { value: 'Panama' },
  { value: 'Saudi Arabia' },
  { value: 'Malaysia' },
  { value: 'Russia' },
  { value: 'Mexico' },
  { value: 'Romania' },
  { value: 'Vietnam' },
  { value: 'Jordan' },
  { value: 'Ecuador' },
  { value: 'Turkey' },
  { value: 'Kuwait' },
  { value: 'Brazil' },
  { value: 'Bolivia' },
  { value: 'Argentina' },
  { value: 'Belarus' },
  { value: 'El Salvador' },
  { value: 'Morocco' },
  { value: 'Guatemala' },
  { value: 'South Africa' },
  { value: 'Honduras' },
  { value: 'Serbia' },
  { value: 'Tunisia' },
  { value: 'Indonesia' },
  { value: 'Thailand' },
  { value: 'Colombia' },
  { value: 'Azerbaijan' },
  { value: 'Philippines' },
  { value: 'Algeria' },
  { value: 'India' },
  { value: 'Paraguay' },
  { value: 'Ukraine' },
  { value: 'Uzbekistan' },
  { value: 'Nepal' },
  { value: 'Tajikistan' },
  { value: 'Nicaragua' },
  { value: 'Egypt' },
  { value: 'Cambodia' },
  { value: 'Sri Lanka' },
  { value: 'Bangladesh' },
  { value: 'Laos' },
  { value: 'Kenya' },
  { value: 'Ghana' },
  { value: 'Pakistan' },
  { value: 'Mali' },
  { value: 'Senegal' },
  { value: 'Botswana' },
  { value: 'Rwanda' },
  { value: 'Burkina Faso' },
  { value: 'Tanzania' },
  { value: 'Benin' },
  { value: 'Malawi' },
  { value: 'Uganda' },
  { value: 'Mozambique' },
  { value: 'Cameroon' },
  { value: 'Niger' },
  { value: 'Togo' },
  { value: 'Guinea' },
  { value: 'Ethiopia' },
  { value: 'Angola' },
  { value: 'Zambia' },
  { value: 'Chad' },
  { value: 'Democratic Republic of Congo' },
  { value: 'Sudan' },
  { value: 'Venezuela' },
  { value: 'Nigeria' },
  { value: 'Burundi' },
  { value: 'Sierra Leone' },
  { value: 'Yemen' },
  { value: 'Haiti' },
  { value: 'Syria' },
];

export default countries;
